export const formData = [
  {
    checked: true,
    description: "This is your public display name.",
    disabled: false,
    label: "UserName",
    name: "name_8066610423",
    placeholder: "shadcn",
    required: true,
    rowIndex: 0,
    type: "text",
    value: "",
    variant: "Input",
  },
  {
    label: "Age",
    name: "age_12345",
    placeholder: "Enter your age",
    required: true,
    rowIndex: 1,
    type: "Number",
    value: "",
    variant: "Input",
  },
  {
    label: "Agree to terms",
    name: "terms_001",
    checked: false,
    required: true,
    rowIndex: 2,
    type: "checkbox",
    variant: "Checkbox",
  },
];
